server:
  port: 8089

spring:
    datasource:
        name: test
        url: jdbc:mysql://127.0.0.1:3306/test?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT&allowMultiQueries=true
        username: root
        password: ROOT
        # 使用druid数据源
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        filters: stat
        maxActive: 20
        initialSize: 1
        maxWait: 60000
        minIdle: 1
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: select 'x'
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxPoolPreparedStatementPerConnectionSize: 20
        maxOpenPreparedStatements: 20
        druid:
              web-stat-filter:
                               enabled: true
              stat-view-servlet:
                                    enabled: true
mybatis:
  mapper-locations: classpath:mapper/*.xml
#  type-aliases-package: com.winterchen.model


mapper:
  mappers:  com.zzg.springcloud.zk.dao.mapper
  not-empty: false
  identity: MYSQL

#pagehelper
pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql
    returnPageInfo: check
